name: Install and test pastebin-ts
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "*.md"
jobs:
  nodejs:
    name: Node.js
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [^14, ^16, ^18]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - uses: codecov/codecov-action@v2
        with:
          files: coverage/lcov.info
          name: ${{ matrix.os }}/${{ matrix.node-version }}
